schema_version = "1.0.0"
id = "LightEditor"
version = "1.2.0"
name = "Light Editor"
tagline = "Adds buttons to quickly switch between mesh display types"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Light-Editor"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]